### ISSUE TITLE
Link directly to choosen showing with filmstaden buy link

### ISSUE THREAD

**Issue by lindskogen** [Filmstund/filmstund#312]
https://www.filmstaden.se/bokning/biljettval/Sys99-SE/AA-1573-201908202045

**Comment by Edholm** [comment]
We have something similar today right? I want to remember that we added a "buy link"

**Comment by lindskogen** [comment]
Yes, but we today we just link to the movie, not the selected showing

**Comment by lindskogen** [comment]
Newer URL: 

https://www.filmstaden.se/bokning/kop/Sys99-SE/20220103-1440-1036

**Comment by lindskogen** [comment]
@Edholm is sfshowing id stored on the showing?

**Comment by Edholm** [comment]
@lindskogen it is! So this should be feasible
