### ISSUE TITLE
Copy highlight string doesn't work

### ISSUE THREAD

**Issue by Edholm** [Filmstund/filmstund#665]
No errors in console but only a single space is actually copied.

<img width="244" alt="bild" src="https://user-images.githubusercontent.com/1151328/148658931-872a4ab2-8bb8-4a4d-99dc-bc88797d049c.png">

**Comment by Edholm** [comment]
hm might be that I tested this with only a single attendee and it doesn't copy the current user...

**Comment by lindskogen** [comment]
Yea, that would be the reason :D
