### ISSUE TITLE
Updating user information (name, nick) doesn't propogate to showing attendees

### ISSUE THREAD

**Issue by Edholm** [Filmstund/filmstund#671]
<img width="291" alt="bild" src="https://user-images.githubusercontent.com/1151328/148679055-33ba6747-2a3f-47d7-b667-0dfa5edb9f45.png">
<img width="344" alt="bild" src="https://user-images.githubusercontent.com/1151328/148679059-e174b084-c186-46d0-9206-345b9447ee75.png">

Reproduce:
* view showing
* change nick
* view same showing again

**Comment by lindskogen** [comment]
Cannot reproduce? What is the exact user flow?

**Comment by Edholm** [comment]
Yeah, might have been a one-off. Can't reproduce now either. Let's close and reopen if needeed.

**Comment by lindskogen** [comment]
Managed to get a repro!

1. Open a showing
2. Go and edit the user
3. Go to "All showings"
4. Go to the showing again
